### ISSUE TITLE
UnsatisfiedLinkError on Android API 18 with Crossexample

### ISSUE THREAD

**Issue by DannyDane** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#127]
First of all thank you for Superpowered SDK. It's possibilties are simply amazing.

When I try to compile the android Crossexample on my API 18 device I get a   java.lang.UnsatisfiedLinkError with a "Unfortunately, CrossExample has stopped" message on the device.

Here's the full error:

06-02 15:52:03.302 27001-27001/com.superpowered.crossexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtof" referenced by "libSuperpoweredExample.so"...
                                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:361)
                                                                                   at java.lang.System.loadLibrary(System.java:525)
                                                                                   at com.superpowered.crossexample.MainActivity.<clinit>(MainActivity.java:125)
                                                                                   at java.lang.Class.newInstanceImpl(Native Method)
                                                                                   at java.lang.Class.newInstance(Class.java:1130)
                                                                                   at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2128)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                                                                                   at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                   at android.os.Looper.loop(Looper.java:137)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                   at dalvik.system.NativeStart.main(Native Method)

On a API 23 device it compiles just fine. Any idea what could be the issue? Thanks in advance.

**Comment by superpoweredSDK** [comment]
What do you mean "compile on my API 18 device"? Compiling happens on your computer.

**Comment by DannyDane** [comment]
I meant to say "run the apk on my device after compiling with Android Studio". Sorry for the confusion.

**Comment by superpoweredSDK** [comment]
Then you don't have the latest Superpowered. Please download it again, this bug was fixed already.
