### ISSUE TITLE
UnsatisfiedLinkError crash on some devices

### ISSUE THREAD

**Issue by gajicm93** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#132]
On some devices (with supported ABI), I get a crash like this on app start while loading library (I'm using latest version of the SDK):

    E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.retrocode.smarting.android, PID: 6528
                                                                              java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtof" referenced by "libSuperpoweredExample.so"...
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                                                  at java.lang.System.loadLibrary(System.java:526)
                                                                                  at com.retrocode.smarting.android.MainActivity.<clinit>(MainActivity.java:186)
                                                                                  at java.lang.Class.newInstanceImpl(Native Method)
                                                                                  at java.lang.Class.newInstance(Class.java:1208)
                                                                                  at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2298)
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:212)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5151)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by superpoweredSDK** [comment]
Please check the latest build settings in the example projects, exactly the platformversion in the build.gradle.

**Comment by gajicm93** [comment]
@superpoweredSDK I can't believe you closed the bug just assuming I was wrong, because I was not, i checked the build.gradle files, and I think they're fine. So see for yourself:

    apply plugin: "com.android.model.application"

    def superpowered_sdk_path = "C:\\Users\\Marko\\Downloads\\Compressed\\SuperpoweredSDK\\Superpowered"

    model {
    repositories {
        libs(PrebuiltLibraries) {
            superpowered { // this is where you declare the "superpowered" static library
                headers.srcDir "${superpowered_sdk_path}"
                binaries.withType(StaticLibraryBinary) { // attaching library files to each platform
                    def platformName = targetPlatform.getName()
                    if (platformName == "armeabi-v7a") {
                        staticLibraryFile = file("${superpowered_sdk_path}/libSuperpoweredAndroidARM.a")
                    } else if (platformName == "arm64-v8a") {
                        staticLibraryFile = file("${superpowered_sdk_path}/libSuperpoweredAndroidARM64.a")
                    } else if (platformName == "x86") {
                        staticLibraryFile = file("${superpowered_sdk_path}/libSuperpoweredAndroidX86.a")
                    } else if (platformName == "x86_64") {
                        staticLibraryFile = file("${superpowered_sdk_path}/libSuperpoweredAndroidX86_64.a")
                    }
                }
            }
        }
    }

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.3"

        defaultConfig {
            applicationId "com.retrocode.smarting.android"
            minSdkVersion.apiLevel 14
            targetSdkVersion.apiLevel 22
            versionCode 1
            versionName "1.4"
        }

        buildTypes {
            release {
                minifyEnabled false
                proguardFiles.add(file("proguard-rules.pro"))
            }
        }
    }

    android.ndk { // your application's native layer parameters
        moduleName = "SuperpoweredExample"
        platformVersion = 16
        stl = "c++_static"
        CFlags.addAll(["-O3", "-fsigned-char"]) // full optimization, char data type is signed
        cppFlags.addAll(["-fexceptions", "-fsigned-char", "-I${superpowered_sdk_path}".toString()])
        ldLibs.addAll(["log", "android", "OpenSLES"]) // load these libraries: log, android, OpenSL ES (for audio)
        abiFilters.addAll(["armeabi-v7a", "arm64-v8a", "x86", "x86_64"]) // these platforms cover 99% percent of all Android devices
    }

    android.sources.main.jni {
        source {
            srcDir "jni"
            srcDir "${superpowered_sdk_path}/AndroidIO"
        }
        dependencies {
            library "superpowered" linkage "static" // this is where you attach the "superpowered" static library to your app
        }
    }
    }

    dependencies {
    compile fileTree(dir: 'libs', include: ['.jar', '.so'])
    compile project(':smartingCommon')
    compile project(':smartingAndroidServices')
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:preference-v14:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    }
