### ISSUE TITLE
UnsatisfiedLinkError crash on some devices

### ISSUE THREAD

**Issue by gajicm93** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#136]
On some devices (with supported ABI), I get a crash like this on app start while loading library (I'm using latest version of the SDK):

    E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.retrocode.smarting.android, PID: 6528
                                                                              java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtof" referenced by "libSuperpoweredExample.so"...
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                                                  at java.lang.System.loadLibrary(System.java:526)
                                                                                  at com.retrocode.smarting.android.MainActivity.<clinit>(MainActivity.java:186)
                                                                                  at java.lang.Class.newInstanceImpl(Native Method)
                                                                                  at java.lang.Class.newInstance(Class.java:1208)
                                                                                  at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2298)
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:212)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5151)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
                                                                                  at dalvik.system.NativeStart.main(Native Method)

This is my build.gradle:

    apply plugin: "com.android.model.application"

    def superpowered_sdk_path = "C:\\Users\\Marko\\Downloads\\Compressed\\SuperpoweredSDK\\Superpowered"

    model {
    repositories {
        libs(PrebuiltLibraries) {
            superpowered { // this is where you declare the "superpowered" static library
                headers.srcDir "${superpowered_sdk_path}"
                binaries.withType(StaticLibraryBinary) { // attaching library files to each platform
                    def platformName = targetPlatform.getName()
                    if (platformName == "armeabi-v7a") {
                        staticLibraryFile = file("${superpowered_sdk_path}/libSuperpoweredAndroidARM.a")
                    } else if (platformName == "arm64-v8a") {
                        staticLibraryFile = file("${superpowered_sdk_path}/libSuperpoweredAndroidARM64.a")
                    } else if (platformName == "x86") {
                        staticLibraryFile = file("${superpowered_sdk_path}/libSuperpoweredAndroidX86.a")
                    } else if (platformName == "x86_64") {
                        staticLibraryFile = file("${superpowered_sdk_path}/libSuperpoweredAndroidX86_64.a")
                    }
                }
            }
        }
    }

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.3"

        defaultConfig {
            applicationId "com.retrocode.smarting.android"
            minSdkVersion.apiLevel 14
            targetSdkVersion.apiLevel 22
            versionCode 1
            versionName "1.4"
        }

        buildTypes {
            release {
                minifyEnabled false
                proguardFiles.add(file("proguard-rules.pro"))
            }
        }
    }

    android.ndk { // your application's native layer parameters
        moduleName = "SuperpoweredExample"
        platformVersion = 16
        stl = "c++_static"
        CFlags.addAll(["-O3", "-fsigned-char"]) // full optimization, char data type is signed
        cppFlags.addAll(["-fexceptions", "-fsigned-char", "-I${superpowered_sdk_path}".toString()])
        ldLibs.addAll(["log", "android", "OpenSLES"]) // load these libraries: log, android, OpenSL ES (for audio)
        abiFilters.addAll(["armeabi-v7a", "arm64-v8a", "x86", "x86_64"]) // these platforms cover 99% percent of all Android devices
    }

    android.sources.main.jni {
        source {
            srcDir "jni"
            srcDir "${superpowered_sdk_path}/AndroidIO"
        }
        dependencies {
            library "superpowered" linkage "static" // this is where you attach the "superpowered" static library to your app
        }
    }
    }

    dependencies {
    compile fileTree(dir: 'libs', include: ['.jar', '.so'])
    compile project(':smartingCommon')
    compile project(':smartingAndroidServices')
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:preference-v14:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    }

**Comment by superpoweredSDK** [comment]
Are those devices below platformVersion 16 please?

**Comment by gajicm93** [comment]
No, it's crashing on Xperia Z1 (4.4.2 stock) and Galaxy Tab 2 7.0 (4.2.2 CyanogenMod). It works on Lollipop devices fine, we tested 3 Lollipop devices.

**Comment by superpoweredSDK** [comment]
What happens if you increase from minSdkVersion.apiLevel 14 to 16?
Android Studio is and this gradle system is still buggy.

**Comment by gajicm93** [comment]
I'll test and report. And I'm using 0.7.2 version of the experimental Gradle plugin, not the alpha you're using, so it should be relatively stable.

**Comment by gajicm93** [comment]
Now I'm getting this. I also updated NDK to lastest stable version 12.    

    E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              java.lang.ExceptionInInitializerError
                                                                                  at java.lang.Class.newInstanceImpl(Native Method)
                                                                                  at java.lang.Class.newInstance(Class.java:1319)
                                                                                  at android.app.Instrumentation.newActivity(Instrumentation.java:1053)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1974)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                                               Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:   791 cannot locate 'strtof'...
                                                                              
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:370)
                                                                                  at java.lang.System.loadLibrary(System.java:535)
                                                                                  at com.retrocode.smarting.android.MainActivity.<clinit>(MainActivity.java:186)
                                                                                  at java.lang.Class.newInstanceImpl(Native Method) 
                                                                                  at java.lang.Class.newInstance(Class.java:1319) 
                                                                                  at android.app.Instrumentation.newActivity(Instrumentation.java:1053) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1974) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                  at android.os.Looper.loop(Looper.java:137) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by superpoweredSDK** [comment]
Unfortunately i can't help as i don't have those devices. I have no idea why it works on new devices well above platformVersion 16, while not on those older devices with platformVersions still above 16...

**Comment by superpoweredSDK** [comment]
We'll release a new version of the library in a few days. It will have no strtof.
